name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: aiplan4eu/upf

    steps:
      - uses: actions/checkout@v2

      - run: git submodule update --init --recursive

      - run: bash run_python_experiment.sh
